# General Jekyll Config

title: Good Product Leaders Community
description: The homepage of the Good Product Leaders Community
logo: https://media.licdn.com/dms/image/D4E22AQGTKBzdYhzUdQ/feedshare-shrink_1280/0/1711178211871?e=1715817600&v=beta&t=7xx4EncExPtQX3wkYDnXCGdcHLBMhQXvEeq-QcwYzoo

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
