# General Jekyll Config

title: Good Product Leaders Community
description: The homepage of the Good Product Leaders Community

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
