# General Jekyll Config

title: Product Leaders Community
description: The WhatsApp Community for Public Sector Product Leaders
logo: https://hineon.com/wp-content/uploads/2021/09/cool-white-neon-triangle-light.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
