# General Jekyll Config

title: Product Leaders Community
description: The WhatsApp Community for Public Sector Product Leaders
logo: https://img.freepik.com/premium-photo/enter-neon-triangle-tunnel-illuminated-with-red-neon-lights-generative-ai-technology_549702-313.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
